spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456


  jpa:
    hibernate:
      ddl-auto: update

#配置日志
logging:
  #配置日志文件路径
  level:
    com.SmartGarden.SmartGarden: debug #不同目录下的日志可配置不同级别
    org.springfromework.web: info
    org.hibernate: error
  #采用相对路径方式将日志文件输出到【log\myspringboot.log】
  file: log\myspringboot.log